### ISSUE TITLE
Installation with OmniSD fails

### ISSUE THREAD

**Issue by derhagen** [strukturart/bHacker-store-client#16]
Hi there,

I know I'm supposed to install the store app manually, which works fine. But for convenience, it would be nice to be able to install it with OmniSD as well, which only shows "Installation error: InvalidPrivilegeLevel" when trying to install. Is this because OmniSD can't install "certified" apps, or could this be fixed easily?

**Comment by strukturart** [comment]
is your device rooted ?

**Comment by derhagen** [comment]
I use the temporary adb root with wallace lite when I need it. Otherwise, no.

**Comment by strukturart** [comment]
**to test**
can you pls try to install this app with OmniSD: https://github.com/strukturart/osm-map/tree/master/build
it is also a "certified" app.

**Comment by derhagen** [comment]
Same issue here. Tried installing with bHackers Store and OmniSD, didn't work for any.

**Comment by strukturart** [comment]
I think it will be difficult to find a solution for this as I use the following api to install apps:
https://developer.mozilla.org/en-US/docs/Archive/Marketplace/API/App_installation_and_management_APIs#Management_API

**Comment by derhagen** [comment]
I see. What kind of root is expected to be present in order to install certified apps via bHackers Store or OmniSD? Is there something like SuperSU for KaiOS to manage apps with root access?

**Comment by strukturart** [comment]
I think with **wallace lite + adb shell** do you have  temporarily  full access to your device

**Comment by derhagen** [comment]
I have used this method to gain root access before. However, as far as I understood you previous posts, I thought I would have to give bHackers store and OmniSD root access to my phone, since they require privileged permissions. Does installing osm-map from bHackers store work on your device?

**Comment by strukturart** [comment]
yes it works on my device, but it is rooted. the store uses the same method of installing apps as omnsd. i have adapted osm-app: "type": "privileged" now you should be able to install without rooting your device. there is a second map app in the store: plastic map with this you can also use maps offline. 

if you want to write apps yourself i would recommend rooting your device, then you have more options.

**Comment by derhagen** [comment]
If you consider having used wallace lite before to open an adb root shell as "being rooted", then my device is rooted, too. I just don't see how that affects the app and this issue, since it doesn't give any app any additional privileges, afaik.

**Comment by strukturart** [comment]
what happens when you try to install osm-app with omnisd ?

**Comment by derhagen** [comment]
As stated above, I get the same error in OmniSD. Just tried the new OSM app and plastic map, both installations fail with the same error, no matter if I try in OmniSD or bHackers store

**Comment by strukturart** [comment]
unfortunately I can't help you, have you already asked here ?
https://discord.gg/TqTMkD

**Comment by Simon-Laux** [comment]
omnisd didn't work for me, too. I guess you need to change a value in the permission db for omnisd being able to install apps?
I haven't tried it yet, but that manual gave me the idea that it could be the permission tables: https://sites.google.com/view/bananahackers/install-omnisd/omnisd-manual-install

Or maybe do I have to use omnisd to put my device in developer mode for it to work?

**Comment by derhagen** [comment]
Carefully re-reading the OmnisSD-instructions, this might be what I forgot: `If everything is fine, press # when the utility is run and confirm the prompt to run the privileged factory reset.`

Will try as soon as I'm home. Maybe that fixes the error in the store app as well.

**Comment by derhagen** [comment]
Enabling the Developer Menu with Wallace Toolbox without a factory reset did the trick for me
