### ISSUE TITLE
Download apps and install from WebStore

### ISSUE THREAD

**Issue by sunsetsonwheels** [strukturart/bHacker-store-client#17]
My WebStore client features a QR code download feature meant for clients on the device to read the QR code and use the provided URL for downloading the package and installing it. It would be great being able to do that on your client :smile:

**Comment by strukturart** [comment]
you mean to include an qr-code reader in the client ?

**Comment by Simon-Laux** [comment]
exactly a qr code reader that reads the qr codes from the webstore.

maybe a qr icon as trigger on the left soft button.

The general idea is that when you a computer, you can browse the app on the computer and can quickly install them on the phone.

**Comment by sunsetsonwheels** [comment]
A warning when the QR code is successfully scanned would be good, since the QR code represents an URL, which might possibly lead to a malicious app if not scanned from say, the WebStore or other 'officially known' clients. Something that says: "You're about to install an app from an external source. By doing so, you accept the terms & conditions as well as licenses of the app. We're not responsible for anything that goes wrong."

**Comment by Simon-Laux** [comment]
theoretically we could also invent a custom uri-scheme like `bhackers:appid`, that way we could simply open the app pages and the user can press the button to install like they would normally do.

**Comment by sunsetsonwheels** [comment]
So, should I change WebStore to generate a QR code with the `bhackers:appid/slug` schema?

**Comment by Simon-Laux** [comment]
as long as we only use the qr code for our appstore we can dictate it's format.

**Comment by sunsetsonwheels** [comment]
Ok then, I will have this change underway on WebStore soon. I will make it encode `bhackers:appid/slug` into a QR code, then the scanning and display implementation can be done here.

So I guess the flow would be:
User finds nice app on WebStore -> clicks Download button -> Use perry's client to scan the code -> client parses code and opens the app details page.

**Comment by sunsetsonwheels** [comment]
Done, the QR code on WebStore now gives a `bhackers:appid/slug`. It can be used however you wish :smile:.

**Comment by Simon-Laux** [comment]
So we basically need two things:
1. scan those qr codes with the app
2. register a uri sheme in the manifest so other qr scanners know that it should be opened with the bhackers store app.

**Comment by Simon-Laux** [comment]
for the second thing we could look it up in the mail app:
in activities section it says:
```json
"view": {
            "filters": {
                "type": "url",
                "url": {
                    "required": true,
                    "pattern": "mailto:.{1,16384}"
                }
            },
            "disposition": "window",
            "href": "/index.html",
            "returnValue": true
        }
```
but I don't know how to listen in the app for that data.
I guess its fine if we ignore that step for now and call this feature done.
(at the moment there isn't an qr code app that opens arbitrary urls with other uri schemes than http and https anyway)
