### ISSUE TITLE
Installation files

### ISSUE THREAD

**Issue by ms1000000** [strukturart/bHacker-store-client#33]
Hey, 
Someone knows if this app store installs the apps automatically or just downloading the zip?
And if it does, can someone write me where are the files that do that?
Thank you very much for your attention.

**Comment by Simon-Laux** [comment]
if it has the rights do do so (after a privileged factory reset for example) it downloads the files to the sdcard and installs them using the https://developer.mozilla.org/en-US/docs/Archive/Marketplace/API/DOMApplicationsRegistry/installPackage api.
See `install.js` in the sources.
The button in the app isn't labeled `install` for no reason.

**Comment by ms1000000** [comment]
Will this HTML code work?

<html>
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        <input type="button" value="Click here to install <package name> package!"                           onclick="installPackage('insert zip file here');" />
    </body>
</html>

**Comment by ms1000000** [comment]
Will this HTML code work?

```
<html>
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        <input type="button" value="Click here to install <package name> package!" onclick="installPackage('insert the package url in omnisd format ::: THE PACKAGE MUST BE IN OMNISD / WEBIDE FORMAT? :::');" />
    </body>
</html>
```

(The javascript is in the onclick event)

**Comment by Simon-Laux** [comment]
nope but this isn't the place to ask. look in https://github.com/strukturart/bHacker-store-client/blob/master/application/assets/js/install.js and ask such general questions on reddit, discord or the banahackers google group if you need more help.
