### ISSUE TITLE
Save data.json content somewhere for future use

### ISSUE THREAD

**Issue by farooqkz** [strukturart/bHacker-store-client#4]

**Comment by strukturart** [comment]
what do you mean with "future use" ?

**Comment by farooqkz** [comment]
The next time user opens the store app. There is no need to download data.json everytime.

**Comment by farooqkz** [comment]
Idea: Let user update data.json everytime by pressing a key or something.
Idea: App itself updates data.json over a prioud of time. For example every hour.
