### ISSUE TITLE
Replace .css("display", "none/block") with show()/hide()

### ISSUE THREAD

**Issue by farooqkz** [strukturart/bHacker-store-client#45]
https://github.com/strukturart/bHacker-store-client/blob/bd68293b51dc347d31ea618052018ce7e630700f/application/app.js#L429-L434

Isn't better to replace those css() calls with simple, readable, show() or hide() calls?

**Comment by farooqkz** [comment]
If you want, I'll create a PR.

**Comment by strukturart** [comment]
I always try the closest css whenever possible. I am currently writing the app in pure js and using mustache to create the elements.

**Comment by farooqkz** [comment]
pure js?why?you'll be wasting your time and energy if you write it in pure js.

@Simon-Laux Don't you think so?

**Comment by strukturart** [comment]
to learn the basics of javascript and the kaisos browser is not really up to date

**Comment by farooqkz** [comment]
I used jQuery for my VM-IRC and had no problem.

**Comment by Simon-Laux** [comment]
My opinion is still use (p)react or pure (non jquery) js.
Also this issue is related to https://github.com/strukturart/bHacker-store-client/issues/27, so in this specific case I recommend solving #27 as it will remove most of these show/hide statements.

**Comment by farooqkz** [comment]
We've got another option, too: Writing our own microframework!

**Comment by jm42** [comment]
Just for reference, two apps ([Here INFO](https://gitlab.com/guide42/hereinfo) and [Guita](https://gitlab.com/guide42/guita)) I created are made in React and works well.
