### ISSUE TITLE
Add option to Email author and maintainers of apps

### ISSUE THREAD

**Issue by farooqkz** [strukturart/bHacker-store-client#51]
Not just showing their emails but also redirecting user to Email app if any.

**Comment by farooqkz** [comment]
The code to do so using [Activities](https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/API/MozActivity):
```javascript
var a = new MozActivity({"name":"view", "data":{"type":"url","url": "mailto:hapu@riseup.net"}});
// then do something with a
```

**Comment by strukturart** [comment]
please make the suggestion to save the developer's e-mail address here.: https://gitlab.com/banana-hackers/store-db/-/tree/master/apps

**Comment by farooqkz** [comment]
I have already done that

**Comment by farooqkz** [comment]
@strukturart You don't want to add this feature to the store app?

**Comment by strukturart** [comment]
Yes why not. if the information is available in the db. every developer can decide whether they want to share their email address. I wouldn't do it myself, if the user has a problem with the app he should write me a github issue.

**Comment by strukturart** [comment]
i can add a button in the options page.

**Comment by farooqkz** [comment]
ah good! Use the code in my second post if you don't know how to invoke Email app.

**Comment by strukturart** [comment]
@farooqkz how would you chop up the author string to find out if an email is included?

**Comment by farooqkz** [comment]
There is no standard for DB, yet but many authors have included their email addresses and many have not done that. Also the author fields of some apps mention more than one author(the store app itself) and there is just one field for this purpose and this makes the situation even worse.

So the recommended strategy for now is that you use a regular expression(compile it once in your code and use it everywhere)
to find all email addresses in author field. Then using mustache(!) add buttons for each email address. Because there is no standard at the moment, title of each button should be "Email the_found_email_addr".

When formatting was standardized, you can write "Email the_name_of_email_owner".

**Comment by farooqkz** [comment]
By the way, when using an RE, it should match email addresses which have more than one dot after `@` and before it for example `farooq.kz@bitcoinshell.mooo.com`

**Comment by farooqkz** [comment]
I would like to contribute so if you let me do it...
