### ISSUE TITLE
Beautify the UI

### ISSUE THREAD

**Issue by farooqkz** [strukturart/bHacker-store-client#54]
At least use better colours.
(I just know that white/gray/black is not beautiful but I don't know which colours together will be beautiful)

**Comment by jm42** [comment]
These are colors from [KaiOS marketing palette](https://developer.kaiostech.com/design-guide/marketing-banner).

Name | Hex
-- | --
Purple | #8500DC
Rose | #CD006F
Red | #FF0E0E
Lime | #6B9A23
Cyan | #00B1B4
Blue | #0071DD
Orange | #FF4B00
Dark Gray | #323232

Might help as reference.

**Comment by farooqkz** [comment]
That's good for reference but I highly recommend that a different look and feel than KaiStore be used.

**Comment by strukturart** [comment]
please make a suggestion with inkscape-> svg then i can try to implement it.
