### ISSUE TITLE
Donation screen shows "<br>" instead of actual linebreaks

### ISSUE THREAD

**Issue by user18130814200115-2** [strukturart/bHacker-store-client#58]
on Nokia 8110 4G

**Comment by farooqkz** [comment]
Confirmed and on many other places which I don't remember right now.
I wanted to report this myself.

**Comment by sunsetsonwheels** [comment]
Confirmed for me too.

**Comment by strukturart** [comment]
please reinstall: https://github.com/strukturart/bHacker-store-client/releases/tag/0.9

**Comment by strukturart** [comment]
done? @user18130814200115-2

**Comment by user18130814200115-2** [comment]
done
