### ISSUE TITLE
Download images and icons only as needed

### ISSUE THREAD

**Issue by farooqkz** [strukturart/bHacker-store-client#65]
Currently the store app downloads all images and icons once in startup and it does not matter if those are displayed or not.
They should be downloaded and then displayed whenever user opens page of an app.

**Comment by strukturart** [comment]
I can try only loading img isInViewport: https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading

--
https://dev.to/spukas/image-lazy-loading-with-pure-javascript-dkh
https://github.com/w3c/IntersectionObserver/tree/master/polyfill

**Comment by strukturart** [comment]
@farooqkz  pls test  the lazyloading thing
