### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by farooqkz** [strukturart/bHacker-store-client#9]
Title says everything. It's about searching between apps.

I think a new tab should be created for it and results should be shown there.

**Comment by strukturart** [comment]
searching by tags/ categories ?

**Comment by farooqkz** [comment]
We don't have much apps in the store right now so the search feature would be useless now. Thus we may put it on low priority.

But for when we want to implement it, I'd suggest that we use everything, title of apps, descriptions, and tags. Also user might be able to search in a certain category or in all categories.
